### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by rgwozdz** [geotrellis/geotrellis-landsat-tutorial#5]
I've stepped through the ReadMe tutorial and started the server, but getting no response in browser.  Note that I am running the tutorial on a Vagrant Ubuntu 16.04 VM, with port 8080 opened to my host machine.

Here's the terminal from the start server command:

![screen shot 2017-01-30 at 4 44 54 pm](https://cloud.githubusercontent.com/assets/4369192/22448064/84e976ea-e70b-11e6-9db0-48751692888e.png)

From the terminal output, does anything appear to be obviously wrong?

**Comment by lossyrob** [comment]
@rgwozdz This looks like everything is in working order. We look for the `Bound to localhost/127.0.0.1:8080` to see the server has started. 

Did you access through `static/index.html`? Hitting port 8080 from the browser wouldn't produce anything, but the endpoints that the index.html page hits are where the functionality would be exposed.

**Comment by rgwozdz** [comment]
Thanks Rob.  I'm trying this URL: http://127.0.0.1:8080/static/index.html

And getting this response:
"The webpage at http://127.0.0.1:8080/static/index.html might be temporarily down or it may have moved permanently to a new web address."

It's strange - I guess it could be some problem with the port forwarding or some configuration on my Vagrant VM -  but for other webservers, the configuration I am using works.  I guess I'll close the issue and assume its something on my end.

**UPDATE**:  When I try a `curl 'http://127.0.0.1:8080/static/index.html'` from the VM terminal, I get a `The requested resource could not be found.` So it can't be the port forwarding...but doesn't necessarily rule out some Ubuntu configuration.

**Comment by mattfullerton** [comment]
Same problem here

**Comment by pomadchin** [comment]
@mattfullerton we can discuss it in our gitter channel: https://gitter.im/geotrellis/geotrellis

though be careful with host names (it may listen to `localhost` but your host has a diff name or smth else, it's an often running on a VM problem as akka can't resolve hostname): https://github.com/geotrellis/geotrellis-landsat-tutorial/blob/master/src/main/scala/tutorial/Serve.scala#L42

**Comment by rgwozdz** [comment]
Not sure what your develop environment is like, but for me, I was trying to connect to 8080 via port-forwarding on a virtual machine.  Had the same response once I switched over to geotrellis-chatta-demo.  What ending up working was installing NGINX on the VM and have all incoming HTTP traffic forwarded to the jetty server port.

On Feb 6, 2017, at 2:58 PM, Grisha <notifications@github.com<mailto:notifications@github.com>> wrote:


@mattfullerton<https://github.com/mattfullerton> we can discuss it in our gitter channel: https://gitter.im/geotrellis/geotrellis

though be careful with host names: https://github.com/geotrellis/geotrellis-landsat-tutorial/blob/master/src/main/scala/tutorial/Serve.scala#L42
